name: Build
on:
 push:
   branches:
	- main
jobs:
  Compile-deploy-dev:
    runs-on:ubuntu-latest
    steps:
      - name:trigger jenkins
	run: curl http://192.168.1.46:8080/job/Commission/build?token=test
